name: Notion Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  notion_to_jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Notion to Markdown
        uses: yatish27/notion-to-github@main
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          output_path: _posts